name: Fetch Playlists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour

permissions:
  contents: write

jobs:
  fetch-playlists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Checkout Data Branch
        uses: actions/checkout@v7
        with:
          ref: data
          path: data
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Fetch Playlists Script
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python playlists/fetch_playlists.py

      - name: Commit and Push to Data Branch
        run: |
          cd data
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add my-automated-playlist.m3u
          if ! git diff --staged --quiet; then
            TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            git commit --amend -m "Automated data: Updated my-automated-playlist.m3u at $TIMESTAMP"
            git push --force origin data
          else
            echo "No my-automated-playlist.m3u changes detected. Skipping commit."
          fi
